[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mr_grok"
version = "1.0.0"
authors = [
  { name="MindRoot" },
]
description = "grok LLM"
requires-python = ">=3.8"
dependencies = [
    "openai"
]
